#!/usr/bin/env python3
"""
Measure each demo's shape and write it into waveforms.js.

The page streams the audio itself straight from clayandkelsy.com, so the only
thing that ships here is the SHAPE — about 200 bytes per song. That's what
lets the rule under each name show the real waveform the instant the page
loads, without downloading a single note.

    tools/waveforms.py

Reads the song URLs out of items.js, so adding an instrument needs no edit
here. Requires ffmpeg (already on this machine). Pure stdlib otherwise.

NEVER hand-edit waveforms.js — re-run this instead.
"""

import base64
import json
import os
import re
import subprocess
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BINS = 200          # columns in the drawn rule
SR   = 8000         # plenty for an envelope


def songs_from_items():
    """Pull every id + song URL out of items.js without executing it."""
    src = open(os.path.join(ROOT, "items.js"), encoding="utf-8").read()
    out = []
    for block in re.split(r"\n  \{", src):
        i = re.search(r"id:\s*'([^']+)'", block)
        s = re.search(r"song:\s*'([^']+)'", block)
        if i and s:
            out.append((i.group(1), s.group(1)))
    return out


def pcm(path_or_url):
    """Mono 8k signed-16 samples via ffmpeg, straight off the wire."""
    p = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", path_or_url,
         "-ac", "1", "-ar", str(SR), "-f", "s16le", "-"],
        capture_output=True)
    if p.returncode != 0:
        raise RuntimeError(p.stderr.decode()[:400])
    import array
    a = array.array("h")
    a.frombytes(p.stdout[: len(p.stdout) // 2 * 2])
    return a


def envelope(samples):
    """
    RMS-led, with peak for the transient jaggedness, then stretched across the
    song's own range so structure shows. A steady piece has no range to
    stretch, and forcing it makes a featureless slab — so leave those alone.
    """
    n = len(samples)
    if n < BINS:
        return [0] * BINS
    per = n // BINS
    vals = []
    for i in range(BINS):
        s, e = i * per, min((i + 1) * per, n)
        tot = 0
        peak = 0
        for j in range(s, e, 3):                 # every 3rd sample is plenty
            v = samples[j]
            tot += v * v
            av = -v if v < 0 else v
            if av > peak:
                peak = av
        cnt = max(1, len(range(s, e, 3)))
        rms = (tot / cnt) ** 0.5
        vals.append(rms * 0.78 + peak * 0.22)

    lo, hi = min(vals), max(vals)
    span = hi - lo
    if span < hi * 0.20:
        vals = [min(1.0, v / hi) * 0.55 if hi else 0 for v in vals]
    else:
        vals = [((v - lo) / span) ** 0.78 for v in vals]
    return [max(0, min(255, round(v * 255))) for v in vals]


def main():
    items = songs_from_items()
    if not items:
        sys.exit("no song: URLs found in items.js")

    out = {}
    for ident, url in items:
        print(f"  {ident:<16} ", end="", flush=True)
        try:
            env = envelope(pcm(url))
            out[ident] = base64.b64encode(bytes(env)).decode()
            print(f"ok  ({len(out[ident])} chars)")
        except Exception as exc:
            print(f"FAILED — {exc}")

    body = ",\n  ".join(f'"{k}": "{v}"' for k, v in out.items())
    js = (
        "/* GENERATED by tools/waveforms.py — do not edit by hand.\n"
        "   One base64 byte per column of the drawn rule; the audio itself is\n"
        f"   streamed from clayandkelsy.com and never ships here. {BINS} columns. */\n"
        "window.WAVES = {\n  " + body + "\n};\n"
    )
    path = os.path.join(ROOT, "waveforms.js")
    open(path, "w", encoding="utf-8").write(js)
    print(f"\nwrote {os.path.relpath(path, ROOT)} — {len(js)} bytes for {len(out)} songs")


if __name__ == "__main__":
    main()
